### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by realvgm** [ArturRod/dicom-ecg#4]
Hi!!

Me again.

Would it be possible to add a horizontal scroll? There are somewhat long ECGs in time and it would be great to have that option.

And one last thing. Is it possible that at the moment of painting the ECG, the waveform was in a higher layer than the time/mV grid? It's silly, but cardiologists prefer it that way.

Thanks for everything!!

**Comment by ArturRod** [comment]
Hi @realvgm 
The scroll theme can apply a scroll from:
`.waveform{
  background: #F9F8F2;
  height: 100%;
  width: 100%;
  overflow: auto;
}
`
Also about the scroll if you are interested there are 2 commented methods that allow you to navigate through the graph drawn c3:
in bindChart ->
`/*zoom: {
        enabled: true,
      },
      subchart: {
        show: true,
      },*/`
Although that is not the problem, do you have an ecg.dicom that can be passed anonymously for testing? Currently the problem is that the ECGs are rendered once (which is how the data arrives) but in other viewers what is done is to repeat that signal and draw it several times, that is why in another viewer the ECG appears longer. I have to do it in the future.

Regarding the maximum or minimum, there are some ranges for each case, you can adjust them as needed:
![image](https://user-images.githubusercontent.com/86238895/182096411-fd89e570-38b3-41a9-b0ca-509ba4b67e9f.png)

**Comment by ArturRod** [comment]
Currently only the hemodynamic ECG is correctly calibrated, I am preparing the calibration for the other views.
![image](https://user-images.githubusercontent.com/86238895/182105866-4c201949-f971-420f-aae4-f4d449c9b701.png)
